-- Spring Batch 5.2.2 - MySQL Drop Schema
-- Source: org/springframework/batch/core/schema-drop-mysql.sql (spring-batch-core-5.2.2)
-- Note: Spring Batch 5 uses BATCH_JOB_SEQ, while Spring Batch 6 renamed it to BATCH_JOB_INSTANCE_SEQ

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ;
